#include "app/window.h"
#include "io/spill_store.h"
#include "core/retouch.h"
#include <sqlite3.h>
#include <cmath>
#include <QAction>
#include <QApplication>
#include <QComboBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDoubleSpinBox>
#include <QFile>
#include <QFileInfo>
#include <QListWidget>
#include <QPushButton>
#include <QSignalSpy>
#include <QTemporaryDir>
#include <QTimer>
#include <QtTest>
#include <algorithm>
#include <array>
#include <functional>
using namespace compositor;
namespace {
QString buildDirectory;
std::shared_ptr<RuntimeResources> resourcesIn(const QString& path) {
 io::SpillLimits limits;limits.maxBytes=64*1024*1024;limits.maxPayloadBytes=2*1024*1024;limits.maxEntries=256;limits.maxIoOperations=1;
 return std::make_shared<RuntimeResources>(ResourceLimits::forMachine(8ull*1024*1024*1024,2),[]{return MemorySample{4ull*1024*1024*1024,64ull*1024*1024};},std::make_shared<io::SpillStore>(path.toStdString(),limits));
}
QByteArray canonical(const engine::RasterSnapshot& raster){QByteArray result;for(auto y=raster.extent.y;y<raster.extent.y+raster.extent.height;++y)for(auto x=raster.extent.x;x<raster.extent.x+raster.extent.width;++x)for(const auto half:engine::pack(raster.pixel(x,y))){result.append(char(half&255));result.append(char(half>>8));}return result;}
QString dialogAction(MainWindow& window,QAction& action,const char* name,const std::function<QString(QDialog&)>& configure,bool cancel=false){bool configured=false,done=false;QString error;QTimer timer;timer.setInterval(10);QElapsedTimer elapsed;elapsed.start();QObject::connect(&timer,&QTimer::timeout,&window,[&]{auto* dialog=qobject_cast<QDialog*>(QApplication::activeModalWidget());if(!dialog)return;if(elapsed.elapsed()>15000){error="Dialog timed out";dialog->reject();return;}if(dialog->objectName()!=QLatin1String(name)){error="Unexpected dialog";dialog->reject();return;}auto* buttons=dialog->findChild<QDialogButtonBox*>();if(!buttons){error="Missing dialog buttons";dialog->reject();return;}if(!configured){if(!buttons->button(QDialogButtonBox::Ok)->isEnabled())return;configured=true;error=configure(*dialog);if(!error.isEmpty())dialog->reject();return;}if(!buttons->button(QDialogButtonBox::Ok)->isEnabled())return;done=true;timer.stop();QTest::mouseClick(buttons->button(cancel?QDialogButtonBox::Cancel:QDialogButtonBox::Ok),Qt::LeftButton);});timer.start();action.trigger();timer.stop();if(!done&&error.isEmpty())error="Dialog closed before acceptance";return error;}
engine::Pixel sample(const engine::RasterSnapshot& source,double x,double y){x-=.5;y-=.5;const auto ix=static_cast<std::int64_t>(std::floor(x)),iy=static_cast<std::int64_t>(std::floor(y));const float fx=static_cast<float>(x-std::floor(x)),fy=static_cast<float>(y-std::floor(y));const std::array<float,4> weights{(1-fx)*(1-fy),fx*(1-fy),(1-fx)*fy,fx*fy};const std::array<engine::Pixel,4> pixels{source.pixel(ix,iy),source.pixel(ix+1,iy),source.pixel(ix,iy+1),source.pixel(ix+1,iy+1)};engine::Pixel result;for(std::size_t i=0;i<4;++i){result.r+=weights[i]*pixels[i].r;result.g+=weights[i]*pixels[i].g;result.b+=weights[i]*pixels[i].b;result.a+=weights[i]*pixels[i].a;}return result;}
std::array<double,3> mean(const engine::RasterSnapshot& source,double x,double y,double radius){const std::array<double,5> weight{1,4,6,4,1};std::array<double,3> result{};double total=0;for(int j=0;j<5;++j)for(int i=0;i<5;++i){const auto value=sample(source,x+(i-2)*radius/2,y+(j-2)*radius/2);const double w=weight[static_cast<std::size_t>(i)]*weight[static_cast<std::size_t>(j)]*value.a;result[0]+=w*value.r/value.a;result[1]+=w*value.g/value.a;result[2]+=w*value.b/value.a;total+=w;}for(auto& value:result)value/=total;return result;}
engine::PackedPixel adjusted(engine::Pixel value){value=engine::unpack(engine::pack(value));const float gain=static_cast<float>(std::exp2(-.5));return engine::pack({value.r*gain,value.g*gain,value.b*gain,value.a});}
}
class D2RetouchWorkflowTest final:public QObject{Q_OBJECT
private slots:void actualToolsReopenStrengthAndExport();};
void D2RetouchWorkflowTest::actualToolsReopenStrengthAndExport(){
 QTemporaryDir directory(QDir(buildDirectory).filePath("d2-retouch-XXXXXX"));QVERIFY(directory.isValid());QImage input(32,16,QImage::Format_RGB32);for(int y=0;y<16;++y)for(int x=0;x<32;++x){const int tone=x<16?70:170;const int detail=x==4&&y==8?35:0;input.setPixel(x,y,qRgb(tone+detail,tone+detail,tone+detail));}const auto path=directory.filePath("source.png");QVERIFY(input.save(path));
 MainWindow window(nullptr,true,{},resourcesIn(directory.path()));window.show();QSignalSpy finished(&window,&MainWindow::operationFinished);qsizetype count=0;
#define COMPLETE(expression) do{++count;expression;QTRY_COMPARE_WITH_TIMEOUT(finished.count(),count,10000);QVERIFY2(finished.last()[0].toBool(),qPrintable(finished.last()[1].toString()));QVERIFY(!window.currentBusy());}while(false)
 COMPLETE(window.openPath(path));const auto original=window.currentDocument();const auto source=original->singleLayer().raster;const auto sourceId=source->id;
 auto* exposure=window.findChild<QAction*>("revisableExposureAction");QVERIFY(exposure);auto error=dialogAction(window,*exposure,"revisableExposureDialog",[](QDialog& dialog){auto* value=dialog.findChild<QDoubleSpinBox*>("revisableExposureValue");if(!value)return QString("Missing exposure");value->setValue(-.5);return QString{};});QVERIFY2(error.isEmpty(),qPrintable(error));++count;QTRY_COMPARE(finished.count(),count);QVERIFY(finished.last()[0].toBool());
 auto* canvas=window.currentCanvas();QVERIFY(canvas);canvas->fit();QTRY_VERIFY_WITH_TIMEOUT(!canvas->captureCpuPresentation().isNull(),10000);
 auto* diameter=window.findChild<QDoubleSpinBox*>("brushDiameter");auto* hardness=window.findChild<QDoubleSpinBox*>("brushHardness");auto* opacity=window.findChild<QDoubleSpinBox*>("brushOpacity");auto* radius=window.findChild<QDoubleSpinBox*>("retouchRadius");QVERIFY(diameter&&hardness&&opacity&&radius);diameter->setValue(2);hardness->setValue(100);opacity->setValue(100);radius->setValue(2);
 const auto point=[&](double x,double y){const auto logical=canvas->viewport().toLogical({x,y});return QPoint(qRound(logical.x),qRound(logical.y));};
 const auto gesture=[&](const char* actionName,double destination){auto* tool=window.findChild<QAction*>(actionName);if(!tool)return false;tool->trigger();canvas->activateCanvas();QTest::mouseClick(canvas,Qt::LeftButton,Qt::AltModifier,point(4.5,8.5));QTest::mousePress(canvas,Qt::LeftButton,{},point(destination,8.5));QTest::mouseRelease(canvas,Qt::LeftButton,{},point(destination,8.5));return true;};
 COMPLETE(QVERIFY(gesture("toolClone",22.5)));const auto cloned=window.currentDocument();QVERIFY(cloned->singleLayer().retouch);QCOMPARE(cloned->singleLayer().retouch->source->id,sourceId);QCOMPARE(canonical(*cloned->singleLayer().retouch->source),canonical(*source));const auto cloneStroke=cloned->singleLayer().retouch->strokes.front();QCOMPARE(cloneStroke.kind,engine::RetouchKind::Clone);const double cloneX=22.5+cloneStroke.sourceAnchor.x-cloneStroke.points.front().x,cloneY=8.5+cloneStroke.sourceAnchor.y-cloneStroke.points.front().y;const auto cloneSample=sample(*source,cloneX,cloneY);QCOMPARE(engine::pack(cloned->singleLayer().raster->pixel(22,8)),adjusted(cloneSample));
 COMPLETE(QVERIFY(gesture("toolHeal",26.5)));const auto healed=window.currentDocument();QCOMPARE(healed->singleLayer().retouch->strokes.size(),std::size_t(2));const auto healStroke=healed->singleLayer().retouch->strokes.back();QCOMPARE(healStroke.kind,engine::RetouchKind::Heal);const double healX=26.5+healStroke.sourceAnchor.x-healStroke.points.front().x,healY=8.5+healStroke.sourceAnchor.y-healStroke.points.front().y;const auto texture=sample(*source,healX,healY);const auto lowSource=mean(*source,healX,healY,2),lowDestination=mean(*source,26.5,8.5,2);const auto base=source->pixel(26,8);const engine::Pixel expectedHeal{static_cast<float>((texture.r/texture.a-lowSource[0]+lowDestination[0])*base.a),static_cast<float>((texture.g/texture.a-lowSource[1]+lowDestination[1])*base.a),static_cast<float>((texture.b/texture.a-lowSource[2]+lowDestination[2])*base.a),base.a};QCOMPARE(engine::pack(healed->singleLayer().raster->pixel(26,8)),adjusted(expectedHeal));QVERIFY(healed->singleLayer().raster->pixel(26,8).r>cloned->singleLayer().raster->pixel(26,8).r);window.undoCurrent();QVERIFY(window.currentDocument()==cloned);window.redoCurrent();QVERIFY(window.currentDocument()==healed);
 const auto project=directory.filePath("retouch.cproj");COMPLETE(window.saveCurrentTo(project));COMPLETE(window.openPath(project));const auto reopened=window.currentDocument();QVERIFY(reopened->singleLayer().retouch);QCOMPARE(reopened->singleLayer().retouch->source->id,sourceId);QVERIFY(reopened->singleLayer().retouch->strokes==healed->singleLayer().retouch->strokes);QVERIFY(reopened->singleLayer().adjustments->operations==healed->singleLayer().adjustments->operations);QCOMPARE(canonical(*reopened->singleLayer().raster),canonical(*healed->singleLayer().raster));
 sqlite3* db=nullptr;QCOMPARE(sqlite3_open_v2(QFile::encodeName(project).constData(),&db,SQLITE_OPEN_READONLY,nullptr),SQLITE_OK);sqlite3_stmt* statement=nullptr;QCOMPARE(sqlite3_prepare_v2(db,"PRAGMA user_version",-1,&statement,nullptr),SQLITE_OK);QCOMPARE(sqlite3_step(statement),SQLITE_ROW);const auto version=sqlite3_column_int(statement,0);sqlite3_finalize(statement);sqlite3_close(db);QCOMPARE(version,6);
 auto* strength=window.findChild<QAction*>("retouchStrengthAction");QVERIFY(strength);error=dialogAction(window,*strength,"retouchStrengthDialog",[](QDialog& dialog){auto* choice=dialog.findChild<QComboBox*>("retouchStrokeChoice");auto* value=dialog.findChild<QDoubleSpinBox*>("retouchStrength");if(!choice||!value||choice->count()!=2)return QString("Missing retained strokes");choice->setCurrentIndex(0);value->setValue(50);return QString{};});QVERIFY2(error.isEmpty(),qPrintable(error));++count;QTRY_COMPARE_WITH_TIMEOUT(finished.count(),count,10000);QVERIFY(finished.last()[0].toBool());const auto revised=window.currentDocument();QCOMPARE(revised->singleLayer().retouch->strokes.front().opacity,.5);QCOMPARE(revised->singleLayer().retouch->strokes.back().opacity,1.);const auto cloneBase=source->pixel(22,8);QCOMPARE(engine::pack(revised->singleLayer().raster->pixel(22,8)),adjusted({(cloneBase.r+cloneSample.r)*.5f,(cloneBase.g+cloneSample.g)*.5f,(cloneBase.b+cloneSample.b)*.5f,1}));window.undoCurrent();QVERIFY(window.currentDocument()==reopened);window.redoCurrent();QVERIFY(window.currentDocument()==revised);
 error=dialogAction(window,*strength,"retouchStrengthDialog",[](QDialog& dialog){auto* value=dialog.findChild<QDoubleSpinBox*>("retouchStrength");if(!value)return QString("Missing strength");value->setValue(0);return QString{};},true);QVERIFY2(error.isEmpty(),qPrintable(error));QCOMPARE(finished.count(),count);QVERIFY(window.currentDocument()==revised);
 for(const auto jpeg:{false,true}){const auto exportPath=directory.filePath(jpeg?"retouch.jpg":"retouch.png");COMPLETE(window.exportCurrentTo(exportPath));const QImage output(exportPath);QVERIFY(!output.isNull());QCOMPARE(output.size(),input.size());double errorSum=0;for(int y=0;y<16;++y)for(int x=0;x<32;++x){const auto pixel=output.pixelColor(x,y);const auto value=revised->singleLayer().raster->pixel(x,y);const auto target=255.0*static_cast<double>(engine::encodeSrgb(value.r));const auto difference=std::abs(static_cast<double>(pixel.red())-target);if(!jpeg)QVERIFY(difference<=1);errorSum+=difference;QCOMPARE(pixel.alpha(),255);}QVERIFY(errorSum/(32*16)<(jpeg?5:1));}
#undef COMPLETE
}
int main(int argc,char** argv){if(argc<2){qCritical("Pass existing disk-backed build directory");return 2;}buildDirectory=QDir(QString::fromLocal8Bit(argv[1])).absolutePath();QApplication app(argc,argv);D2RetouchWorkflowTest test;return QTest::qExec(&test,argc-1,argv+1);}
#include "d2_retouch_workflow_test.moc"
