#include "core/image_resize.h"
#include "core/editor_commands.h"
#include "core/retouch.h"
#include "core/resources.h"
#include <iostream>
#include <cmath>
using namespace compositor::engine;
using compositor::MemoryAdmission;
using compositor::MemorySample;
namespace {
void expect(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F operation){bool rejected=false;try{operation();}catch(const std::exception&){rejected=true;}expect(rejected,"Expected resize rejection");}
DocumentPtr fixture(TileStore& store){const std::array<Pixel,4> pixels{{{.125f,0,0,.25f},{0,.25f,0,.5f},{0,0,.5f,1},{.125f,.25f,.375f,.5f}}};TileMap tiles;tiles.emplace(TileCoord{0,0},store.create(2,2,pixels));LayerNode node{Id::generate()};node.raster=std::make_shared<const RasterSnapshot>(Id::generate(),Extent{0,0,2,2},PackedPixel{},std::move(tiles));return std::make_shared<const DocumentSnapshot>(Id::generate(),2,2,150,std::vector<LayerNode>{node},0);}
}
int main(){try{
 TileStore store(64*1024*1024);const auto source=fixture(store);DocumentHistory history(source);expect(history.commit(resampleDocument(source,store,4,4,Sampling::Nearest),"Image resize"),"Resize commits");const auto enlarged=history.current();expect(enlarged->width==4 && enlarged->height==4 && enlarged->resolution==150,"Canvas and DPI");const auto& raster=*enlarged->singleLayer().raster;expect(raster.extent==Extent{0,0,4,4},"Actual source grid resized");for(int y=0;y<4;++y)for(int x=0;x<4;++x)expect(pack(raster.pixel(x,y))==pack(source->singleLayer().raster->pixel(x/2,y/2)),"Nearest independent pixel mapping");expect(enlarged->singleLayer().localToDocument==Affine{},"Identity placement preserved");expect(history.undo() && history.current()==source && history.redo() && history.current()==enlarged,"Single undo redo");
 const auto reduced=resampleDocument(source,store,1,1,Sampling::Bilinear).finish(1);Pixel average{};for(int y=0;y<2;++y)for(int x=0;x<2;++x){const auto pixel=source->singleLayer().raster->pixel(x,y);average.r+=pixel.r*.25f;average.g+=pixel.g*.25f;average.b+=pixel.b*.25f;average.a+=pixel.a*.25f;}expect(pack(reduced->singleLayer().raster->pixel(0,0))==pack(average),"Bilinear premultiplied alpha mean");
 LayerNode solid{Id::generate()};TileMap solidTiles;std::array<Pixel,4> uniform;uniform.fill(Pixel{.125f,.25f,.375f,.5f});solidTiles.emplace(TileCoord{0,0},store.create(2,2,uniform));solid.raster=std::make_shared<const RasterSnapshot>(Id::generate(),Extent{0,0,2,2},PackedPixel{},std::move(solidTiles));auto uniformDoc=std::make_shared<const DocumentSnapshot>(Id::generate(),2,2,72,std::vector<LayerNode>{solid},0);const auto lanczos=resampleDocument(uniformDoc,store,1,1,Sampling::Lanczos).finish(1);expect(pack(lanczos->singleLayer().raster->pixel(0,0))==pack(uniform[0]),"Lanczos edge clamp preserves uniform RGBA");
 auto nodes=source->layers();auto& node=nodes.front();node.localToDocument={.8,.3,-.2,1.1,.5,-.5};node.mask=std::make_shared<const RasterSnapshot>(Id::generate(),node.raster->extent,pack(Pixel{0,0,0,.75f}));node.maskEnabled=false;Selection selection{Extent{0,0,1,1},SelectionShape::Ellipse,true,2};auto contextual=std::make_shared<const DocumentSnapshot>(source->id,2,2,150,nodes,0,selection);const auto transformed=resampleDocument(contextual,store,4,6,Sampling::Nearest).finish(1);const auto& next=transformed->singleLayer();expect(next.mask && next.mask->extent==next.raster->extent && !next.maskEnabled,"Linked mask grid and enable");expect(pack(next.mask->pixel(0,0))==pack(Pixel{0,0,0,.75f}),"Mask coverage");const auto oldPoint=node.localToDocument.map({1,1});const auto newPoint=next.localToDocument.map({2,3});expect(std::abs(newPoint.x-2*oldPoint.x)<1e-12 && std::abs(newPoint.y-3*oldPoint.y)<1e-12,"Affine D A B inverse geometry");expect(transformed->selection && transformed->selection->bounds==Extent{0,0,2,3} && transformed->selection->inverted && transformed->selection->shape==SelectionShape::Ellipse,"Selection bounds and kind");expect(std::abs(transformed->selection->featherRadius-2*std::sqrt(6.))<1e-12,"Selection feather geometric scaling");
 AdjustmentParameters exposure{AdjustmentKind::Exposure,1};const auto adjusted=setRevisableAdjustments(source,source->singleLayer().id,store,{exposure}).finish(1);const auto adjustedResize=resampleDocument(adjusted,store,4,4,Sampling::Nearest).finish(2);expect(adjustedResize->singleLayer().adjustments && adjustedResize->singleLayer().adjustments->operations==std::vector<AdjustmentParameters>{exposure},"Retained adjustment controls");expect(adjustedResize->singleLayer().adjustments->source->extent==Extent{0,0,4,4},"Retained source actually resized");const auto reference=setRevisableAdjustments(enlarged,enlarged->singleLayer().id,store,{exposure}).finish(2);for(int y=0;y<4;++y)for(int x=0;x<4;++x)expect(pack(adjustedResize->singleLayer().raster->pixel(x,y))==pack(reference->singleLayer().raster->pixel(x,y)),"Resized source replay exact pixels");
 RetouchStroke stroke;stroke.kind=RetouchKind::Clone;stroke.sourceAnchor={.5,.5};stroke.points={{1.5,1.5}};stroke.diameter=1;stroke.hardness=1;stroke.canvasWidth=2;stroke.canvasHeight=2;const auto retouched=setRetouchStrokes(source,source->singleLayer().id,store,{stroke}).finish(1);const auto mixed=setRevisableAdjustments(retouched,retouched->singleLayer().id,store,{exposure}).finish(2);const auto mixedResize=resampleDocument(mixed,store,4,6,Sampling::Nearest).finish(3);const auto& retained=mixedResize->singleLayer();expect(retained.retouch && retained.adjustments && retained.retouch->source->extent==Extent{0,0,4,6},"Retouch original retained before adjustments");const auto& mapped=retained.retouch->strokes.front();expect(mapped.points.size()==stroke.points.size() && mapped.points.front().x==stroke.points.front().x && mapped.points.front().y==stroke.points.front().y && mapped.sourceAnchor.x==stroke.sourceAnchor.x && mapped.sourceAnchor.y==stroke.sourceAnchor.y && mapped.diameter==stroke.diameter && mapped.canvasWidth==stroke.canvasWidth,"Frozen stroke coordinates remain captured frame");expect(mapped.localToDocument.a==.5 && std::abs(mapped.localToDocument.d-1./3)<1e-12,"Frozen stroke mapping follows new source grid");expect(retained.adjustments->source->extent==retained.raster->extent,"Retouch and adjustment source grid relationship");
 LayerNode shifted{Id::generate()};shifted.raster=std::make_shared<const RasterSnapshot>(Id::generate(),Extent{-2,3,2,2},pack(Pixel{.125f,.25f,.375f,.5f}));shifted.localToDocument.tx=2;shifted.localToDocument.ty=-3;const auto shiftedDoc=std::make_shared<const DocumentSnapshot>(Id::generate(),2,2,72,std::vector<LayerNode>{shifted},0);const auto shiftedResize=resampleDocument(shiftedDoc,store,4,6,Sampling::Nearest).finish(1);expect(shiftedResize->singleLayer().raster->extent==Extent{0,0,4,6} && shiftedResize->singleLayer().localToDocument==Affine{},"Nonzero source origin normalized with exact placement");
 std::stop_source midway;int probes=0;auto cancellationMemory=std::make_shared<MemoryAdmission>(32*1024*1024,0,[&]{if(++probes==2)midway.request_stop();return MemorySample{1024*1024*1024,0};});TileStore cancellationStore(32*1024*1024,cancellationMemory);rejects([&]{resampleDocument(source,cancellationStore,4,4,Sampling::Nearest,midway.get_token());});expect(probes>=2 && cancellationStore.usedBytes()==0 && cancellationMemory->snapshot().committedCpu==0 && cancellationMemory->snapshot().pendingCpu==0,"Mid-operation cancellation releases prepared output and scratch");
 auto lifetimeMemory=std::make_shared<MemoryAdmission>(32*1024*1024,0,[]{return MemorySample{1024*1024*1024,0};});DocumentPtr lifetimeDocument;Tile::ReadLease retainedLease;{TileStore lifetimeStore(32*1024*1024,lifetimeMemory);lifetimeDocument=resampleDocument(source,lifetimeStore,4,4,Sampling::Nearest).finish(1);expect(lifetimeMemory->snapshot().committedCpu>128,"Resized raster metadata lifetime is admitted");retainedLease=lifetimeDocument->singleLayer().raster->tiles.begin()->second->read();}expect(lifetimeMemory->snapshot().committedCpu>0,"Owner destruction keeps result charges");lifetimeDocument.reset();expect(lifetimeMemory->snapshot().committedCpu>0,"Read lease retains tile charges independently of resized graph");retainedLease={};expect(lifetimeMemory->snapshot().committedCpu==0 && lifetimeMemory->snapshot().pendingCpu==0,"Final graph and lease release all charges");
 const auto before=store.usedBytes();std::stop_source stop;stop.request_stop();rejects([&]{resampleDocument(source,store,4,4,Sampling::Lanczos,stop.get_token());});expect(store.usedBytes()==before,"Canceled resize retains no output");auto deniedMemory=std::make_shared<MemoryAdmission>(1,0,[]{return MemorySample{1024*1024*1024,0};});TileStore denied(64*1024*1024,deniedMemory);rejects([&]{resampleDocument(source,denied,4,4,Sampling::Lanczos);});expect(denied.usedBytes()==0 && deniedMemory->snapshot().committedCpu==0,"Admission refusal retains no tiles or charges");expect(resampleDocument(source,store,2,2,Sampling::Lanczos).finish(1)==source,"Same size exact no-op");rejects([&]{resampleDocument(source,store,30000,30000,Sampling::Nearest);});rejects([&]{resampleDocument(source,store,4,4,static_cast<Sampling>(99));});
 std::cout<<"Image resize tests passed\n";return 0;
 }catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
