#include "core/retouch.h"
#include "core/editor_commands.h"
#include <array>
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>
using namespace compositor;
using namespace compositor::engine;
namespace {
void expect(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F operation){bool rejected=false;try{operation();}catch(const std::exception&){rejected=true;}expect(rejected,"Invalid retouch accepted");}
DocumentPtr fixture(TileStore& store,bool detail=false){std::vector<Pixel> pixels(11*5);for(int y=0;y<5;++y)for(int x=0;x<11;++x){float value=x<5?.2f:.8f;if(detail&&x==2&&y==2)value=.3f;pixels[static_cast<std::size_t>(y*11+x)]={value*.5f,value*.25f,value*.125f,.5f};}TileMap tiles;tiles.emplace(TileCoord{0,0},store.create(11,5,pixels));auto profile=std::make_shared<const SourceProfile>(SourceProfile{Id::generate(),{1,2,3}});auto source=std::make_shared<const RasterSnapshot>(Id::generate(),Extent{0,0,11,5},PackedPixel{},std::move(tiles),0,profile);return std::make_shared<const DocumentSnapshot>(Id::generate(),Id::generate(),11,5,144,source);}
RetouchStroke stroke(RetouchKind kind=RetouchKind::Clone){RetouchStroke result;result.kind=kind;result.sourceAnchor={2.5,2.5};result.points={{8.5,2.5}};result.diameter=1;result.hardness=1;result.healingRadius=2;result.canvasWidth=11;result.canvasHeight=5;return result;}
void cloneStrengthSourceAndHistory(){TileStore store(16*1024*1024);auto input=fixture(store);const auto id=input->singleLayer().id;const auto original=input->singleLayer().raster;auto full=stroke();DocumentHistory history(input);expect(history.commit(setRetouchStrokes(input,id,store,{full}),"Clone"),"Missing clone edit");auto first=history.current();expect(pack(first->singleLayer().raster->pixel(8,2))==pack(original->pixel(2,2)),"Clone did not copy anchored source");expect(first->singleLayer().retouch->source==original,"Clone lost retained source");full.opacity=.5;expect(history.commit(setRetouchStrokes(first,id,store,{full}),"Strength"),"Missing strength edit");auto revised=history.current();const auto a=original->pixel(2,2),b=original->pixel(8,2);expect(pack(revised->singleLayer().raster->pixel(8,2))==pack({(a.r+b.r)*.5f,(a.g+b.g)*.5f,(a.b+b.b)*.5f,.5f}),"Strength compounded old clone");expect(history.undo()&&history.current()==first&&history.redo()&&history.current()==revised,"Retouch undo/redo failed");expect(setRetouchStrokes(revised,id,store,{full}).finish(9)==revised,"Same stroke was not a no-op");auto removed=setRetouchStrokes(revised,id,store,{}).finish(9);expect(!removed->singleLayer().retouch&&removed->singleLayer().raster==original,"Removing strokes did not restore source");expect(pack(original->pixel(8,2))==pack(b),"Source was mutated");}
void healingTransfersDetailAndDestinationTone(){TileStore store(16*1024*1024);auto plain=fixture(store);auto heal=stroke(RetouchKind::Heal);auto unchanged=setRetouchStrokes(plain,plain->singleLayer().id,store,{heal}).finish(1);expect(pack(unchanged->singleLayer().raster->pixel(8,2))==pack(plain->singleLayer().raster->pixel(8,2)),"Healing constant texture must retain destination tone");auto input=fixture(store,true);auto result=setRetouchStrokes(input,input->singleLayer().id,store,{heal}).finish(1);const auto source=input->singleLayer().raster;const double sourceCenter=source->pixel(2,2).r/.5;const double sourceBase=source->pixel(1,2).r/.5;const double destination=source->pixel(8,2).r/.5;const double sourceMean=sourceBase+(sourceCenter-sourceBase)*36/256;const auto actual=result->singleLayer().raster->pixel(8,2);expect(toHalf(actual.r)==toHalf(static_cast<float>((sourceCenter-sourceMean+destination)*.5)),"Healing differs from independent Gaussian detail-transfer result");expect(actual.a==source->pixel(8,2).a,"Healing changed destination alpha");expect(actual.r>source->pixel(8,2).r&&actual.r>source->pixel(2,2).r,"Healing failed to combine source detail and destination tone");}
void softSelectionTransformAndOrderedStages(){TileStore store(16*1024*1024);auto input=fixture(store);auto settings=stroke();settings.diameter=4;settings.hardness=0;auto soft=setRetouchStrokes(input,input->singleLayer().id,store,{settings}).finish(1);const auto value=soft->singleLayer().raster->pixel(8,2).r;expect(value>input->singleLayer().raster->pixel(2,2).r&&value<input->singleLayer().raster->pixel(8,2).r,"Soft brush lacks feathered coverage");settings=stroke();settings.selection=Selection{Extent{0,0,4,5}};auto excluded=setRetouchStrokes(input,input->singleLayer().id,store,{settings}).finish(1);expect(pack(excluded->singleLayer().raster->pixel(8,2))==pack(input->singleLayer().raster->pixel(8,2)),"Selection did not restrict clone");settings.selection->inverted=true;auto selected=setRetouchStrokes(input,input->singleLayer().id,store,{settings}).finish(1);expect(pack(selected->singleLayer().raster->pixel(8,2))==pack(input->singleLayer().raster->pixel(2,2)),"Inverted selection lost clone");settings=stroke();settings.localToDocument.tx=2;settings.sourceAnchor.x+=2;settings.points[0].x+=2;settings.canvasWidth=13;auto transformed=setRetouchStrokes(input,input->singleLayer().id,store,{settings}).finish(1);expect(pack(transformed->singleLayer().raster->pixel(8,2))==pack(input->singleLayer().raster->pixel(2,2)),"Frozen document mapping was ignored");auto first=stroke(),second=stroke();second.sourceAnchor={8.5,2.5};second.points={{6.5,2.5}};auto ordered=setRetouchStrokes(input,input->singleLayer().id,store,{first,second}).finish(1);expect(pack(ordered->singleLayer().raster->pixel(6,2))==pack(input->singleLayer().raster->pixel(2,2)),"Later stroke did not sample prior immutable stage");}
void adjustmentsAndMasksRetainRevisability(){TileStore store(16*1024*1024);auto input=fixture(store);const auto id=input->singleLayer().id;auto adjusted=setRevisableAdjustments(input,id,store,{{AdjustmentKind::Exposure,1}}).finish(1);auto masked=createLayerMask(adjusted,id,store,false).finish(2);auto result=setRetouchStrokes(masked,id,store,{stroke()}).finish(3);const auto& layer=result->singleLayer();expect(layer.retouch->source==input->singleLayer().raster,"Retouch started from adjusted pixels");expect(layer.adjustments&&layer.adjustments->source!=layer.retouch->source,"Adjustment source did not follow retouch");expect(layer.mask==masked->singleLayer().mask&&layer.raster->sourceProfile==input->singleLayer().raster->sourceProfile,"Retouch changed mask/profile");const auto a=input->singleLayer().raster->pixel(2,2);expect(pack(layer.raster->pixel(8,2))==pack({a.r*2,a.g*2,a.b*2,a.a}),"Adjustment was not replayed after retouch");auto restored=setRetouchStrokes(result,id,store,{}).finish(4);expect(!restored->singleLayer().retouch&&restored->singleLayer().adjustments->source==input->singleLayer().raster,"Removing retouch failed adjustment-source restoration");}
void retainedMetadataAdmissionLifetime(){auto memory=std::make_shared<MemoryAdmission>(32*1024*1024,0,[]{return MemorySample{64*1024*1024,0};});TileStore store(16*1024*1024,memory);auto input=fixture(store);const auto baseline=memory->snapshot().committedCpu;auto output=setRetouchStrokes(input,input->singleLayer().id,store,{stroke()}).finish(1);auto retained=output->singleLayer().retouch;expect(memory->snapshot().committedCpu>baseline,"Retouch metadata not admitted");output.reset();expect(memory->snapshot().committedCpu>baseline,"Retained stroke charge did not survive document destruction");retained.reset();expect(memory->snapshot().committedCpu==baseline&&memory->snapshot().pendingCpu==0,"Retouch metadata charge leaked after backing release");}
void boundsCancellationAndAdmission(){TileStore store(16*1024*1024);auto input=fixture(store);const auto source=input->singleLayer().raster;auto valid=stroke();RetouchStack stack{source,{valid},1};validateRetouchStack(stack,*source);stack.policy=2;rejects([&]{validateRetouchStack(stack,*source);});stack.policy=1;stack.strokes.clear();rejects([&]{validateRetouchStack(stack,*source);});stack.strokes.assign(17,valid);rejects([&]{validateRetouchStack(stack,*source);});stack.strokes={valid};stack.strokes[0].opacity=std::numeric_limits<double>::quiet_NaN();rejects([&]{validateRetouchStack(stack,*source);});std::stop_source stopped;stopped.request_stop();rejects([&]{setRetouchStrokes(input,input->singleLayer().id,store,{valid},stopped.get_token());});auto memory=std::make_shared<MemoryAdmission>(1,0,[]{return MemorySample{1024*1024,0};});TileStore denied(16*1024*1024,memory);rejects([&]{setRetouchStrokes(input,input->singleLayer().id,denied,{valid});});expect(!input->singleLayer().retouch,"Failed retouch published metadata");expect(source==input->singleLayer().raster,"Failed retouch changed source");}
}
int main(){try{cloneStrengthSourceAndHistory();healingTransfersDetailAndDestinationTone();softSelectionTransformAndOrderedStages();adjustmentsAndMasksRetainRevisability();boundsCancellationAndAdmission();retainedMetadataAdmissionLifetime();std::cout<<"6 retouch test groups passed\n";return 0;}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
