#include "core/editor_commands.h"
#include "io/project_store.h"
#include "io/adjustment_parameters.h"
#include <QCoreApplication>
#include <QTemporaryDir>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <sqlite3.h>
#include <lcms2.h>
#include <iostream>
using namespace compositor::engine;
using namespace compositor::io;
namespace {
void expect(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F> void rejects(F f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}expect(rejected,"Expected rejection");}
void change(const QString& path,const char* sql){sqlite3* db=nullptr;expect(sqlite3_open(path.toUtf8().constData(),&db)==SQLITE_OK,"Open mutation");const auto rc=sqlite3_exec(db,sql,nullptr,nullptr,nullptr);sqlite3_close(db);expect(rc==SQLITE_OK,"Mutation");}
}
int main(int argc,char** argv){QCoreApplication app(argc,argv);try {
 QTemporaryDir directory(QCoreApplication::applicationDirPath()+"/revisable-persistence-XXXXXX");expect(directory.isValid(),"Fixture directory");TileStore tiles(32*1024*1024);
 const auto native=cmsCreate_sRGBProfile();expect(native!=nullptr,"Profile fixture");cmsUInt32Number size=0;expect(cmsSaveProfileToMem(native,nullptr,&size),"Profile size");std::vector<std::uint8_t> bytes(size);expect(cmsSaveProfileToMem(native,bytes.data(),&size),"Profile encode");cmsCloseProfile(native);auto profile=std::make_shared<const SourceProfile>(SourceProfile{Id::generate(),std::move(bytes)});
 LayerNode layer{Id::generate()};layer.raster=std::make_shared<const RasterSnapshot>(Id::generate(),Extent{0,0,2,1},pack(Pixel{.125f,.25f,.375f,.5f}),TileMap{},0,profile);
 layer.mask=std::make_shared<const RasterSnapshot>(Id::generate(),Extent{0,0,2,1},pack(Pixel{0,0,0,.75f}));layer.localToDocument.tx=1;
 auto original=std::make_shared<const DocumentSnapshot>(Id::generate(),4,2,150,std::vector<LayerNode>{layer},0,Selection{Extent{0,0,2,1}});
 AdjustmentParameters exposure{AdjustmentKind::Exposure,1};AdjustmentParameters levels;levels.kind=AdjustmentKind::Levels;levels.levels.gamma=1.5;
 DocumentHistory history(original);expect(history.commit(setRevisableAdjustments(original,layer.id,tiles,{exposure,levels}),"Revisable"),"Commit stack");
 auto nodes=history.current()->layers();auto duplicate=nodes.front();duplicate.id=Id::generate();duplicate.siblingOrder=1;duplicate.sampling=Sampling::Lanczos;nodes.push_back(duplicate);
 auto edited=std::make_shared<const DocumentSnapshot>(original->id,4,2,150,nodes,history.current()->revision,original->selection);
 const auto path=directory.filePath("stack.cproj");const auto identity=saveProject(path,edited);auto loaded=loadProject(path,tiles).document;
 const auto& reopened=loaded->layer(layer.id);expect(reopened.adjustments && reopened.adjustments->operations==std::vector<AdjustmentParameters>{exposure,levels},"Exact operation parameters");
 expect(reopened.adjustments->source->id==layer.raster->id && pack(reopened.adjustments->source->pixel(0,0))==pack(layer.raster->pixel(0,0)),"Retained source");
 expect(reopened.raster->id==edited->layer(layer.id).raster->id && reopened.raster->revision==edited->layer(layer.id).raster->revision && pack(reopened.raster->pixel(0,0))==pack(edited->layer(layer.id).raster->pixel(0,0)),"Effective raster identity and pixels");
 expect(reopened.adjustments->source->sourceProfile && reopened.adjustments->source->sourceProfile->bytes==profile->bytes,"Profile bytes");
 expect(reopened.raster==loaded->layer(duplicate.id).raster && loaded->layer(duplicate.id).sampling==Sampling::Lanczos,"Shared derived cache and independent sampling");expect(reopened.mask && reopened.localToDocument==layer.localToDocument && loaded->selection==original->selection,"Mask placement selection");
 exposure.value=-1;const auto revised=setRevisableAdjustments(loaded,layer.id,tiles,{exposure}).finish(loaded->revision+1);const auto expected=setRevisableAdjustments(original,layer.id,tiles,{exposure}).finish(1);
 expect(pack(revised->layer(layer.id).raster->pixel(0,0))==pack(expected->layer(layer.id).raster->pixel(0,0)),"Reopened revision starts from source");
 std::stop_source stop;stop.request_stop();rejects([&]{loadProject(path,tiles,stop.get_token());});SaveOptions cancelled;cancelled.expected=identity;cancelled.stop=stop.get_token();rejects([&]{saveProject(path,revised,cancelled);});expect(fileIdentity(path)==identity,"Canceled save preserves old file");
 const auto record=adjustmentParameters(*reopened.adjustments,*reopened.raster,reopened.sampling);rejects([&]{readAdjustmentParameters(record+" ",reopened.adjustments->source);});
 auto malformed=record;auto policy=malformed.find("\"policy\":2");expect(policy!=std::string::npos,"Policy fixture");malformed.replace(policy,10,"\"policy\":9");rejects([&]{readAdjustmentParameters(malformed,reopened.adjustments->source);});
 AdjustmentParameters neutral{AdjustmentKind::Exposure,0};const auto neutralDoc=setRevisableAdjustments(original,layer.id,tiles,{neutral}).finish(1);const auto neutralPath=directory.filePath("neutral.cproj");saveProject(neutralPath,neutralDoc);const auto neutralLoaded=loadProject(neutralPath,tiles).document;expect(neutralLoaded->layer(layer.id).adjustments && neutralLoaded->layer(layer.id).adjustments->operations==std::vector<AdjustmentParameters>{neutral},"Neutral retained stack round trip");
 auto wrongSource=std::make_shared<const RasterSnapshot>(Id::generate(),layer.raster->extent,layer.raster->defaultValue);rejects([&]{readAdjustmentParameters(record,wrongSource);});
 auto unknown=record;const auto operationPosition=unknown.find("\"operations\":[[0,");expect(operationPosition!=std::string::npos,"Operation fixture");unknown.replace(operationPosition,16,"\"operations\":[[99,");rejects([&]{readAdjustmentParameters(unknown,reopened.adjustments->source);});
 auto nonfinite=record;const auto scalarPosition=nonfinite.find("[[0,1,");expect(scalarPosition!=std::string::npos,"Scalar fixture");nonfinite.replace(scalarPosition,6,"[[0,NaN,");rejects([&]{readAdjustmentParameters(nonfinite,reopened.adjustments->source);});
 change(path,"UPDATE layers SET parameters_json=replace(parameters_json,'\"policy\":2','\"policy\":9')");rejects([&]{loadProject(path,tiles);});
 AdjustmentParameters curves;curves.kind=AdjustmentKind::Curves;curves.curve={{0,0},{.5,.7},{1,1}};
 const auto curveDoc=setRevisableAdjustments(original,layer.id,tiles,{curves}).finish(1);
 auto legacyNodes=curveDoc->layers();auto legacyStack=std::make_shared<AdjustmentStack>(*legacyNodes.front().adjustments);legacyStack->policy=1;legacyNodes.front().adjustments=legacyStack;
 auto legacyDoc=std::make_shared<const DocumentSnapshot>(original->id,4,2,150,legacyNodes,1,original->selection);const auto legacyPath=directory.filePath("legacy-curves-v4.cproj");saveProject(legacyPath,legacyDoc);
 auto legacyObject=QJsonDocument::fromJson(QByteArray::fromStdString(adjustmentParameters(*legacyStack,*legacyNodes.front().raster,legacyNodes.front().sampling))).object();legacyObject.insert("version",2);auto legacyOperations=legacyObject.value("operations").toArray();for(int i=0;i<legacyOperations.size();++i){auto op=legacyOperations[i].toArray();op.removeLast();legacyOperations[i]=op;}legacyObject.insert("operations",legacyOperations);const auto legacyRecord=QJsonDocument(legacyObject).toJson(QJsonDocument::Compact);
 sqlite3* legacyDb=nullptr;expect(sqlite3_open(legacyPath.toUtf8().constData(),&legacyDb)==SQLITE_OK,"Legacy mutation open");sqlite3_stmt* statement=nullptr;expect(sqlite3_prepare_v2(legacyDb,"UPDATE layers SET parameters_json=?",-1,&statement,nullptr)==SQLITE_OK,"Legacy query");expect(legacyRecord.size()<=32768,"Bounded legacy record");expect(sqlite3_bind_text(statement,1,legacyRecord.constData(),static_cast<int>(legacyRecord.size()),SQLITE_TRANSIENT)==SQLITE_OK,"Legacy parameter binding");expect(sqlite3_step(statement)==SQLITE_DONE,"Legacy parameter conversion");sqlite3_finalize(statement);expect(sqlite3_exec(legacyDb,"UPDATE project SET selection_json='{\"version\":1,\"shape\":\"rectangle\",\"bounds\":[0,0,2,1],\"inverted\":false}'; PRAGMA user_version=4",nullptr,nullptr,nullptr)==SQLITE_OK,"Legacy version");sqlite3_close(legacyDb);
 const auto legacyLoaded=loadProject(legacyPath,tiles).document;expect(legacyLoaded->singleLayer().adjustments->policy==1 && legacyLoaded->singleLayer().adjustments->operations==std::vector<AdjustmentParameters>{curves},"Version4 policy1 channel identity materialization");expect(pack(legacyLoaded->singleLayer().raster->pixel(0,0))==pack(curveDoc->singleLayer().raster->pixel(0,0)),"Legacy Curves cache exact bits");expect(legacyLoaded->singleLayer().raster->id==curveDoc->singleLayer().raster->id,"Legacy cache UUID");
 const auto noop=setRevisableAdjustments(legacyLoaded,layer.id,tiles,{curves}).finish(legacyLoaded->revision+1);expect(noop==legacyLoaded,"Legacy unchanged stack no-op");
 const auto migratedPath=directory.filePath("legacy-saved-v5.cproj");saveProject(migratedPath,legacyLoaded);const auto migrated=loadProject(migratedPath,tiles).document;expect(migrated->singleLayer().adjustments->policy==1,"Resave preserves legacy policy");
 curves.channelCurves[0]={{0,0},{.5,.3},{1,1}};curves.channelCurves[1]={{0,0},{.5,.8},{1,1}};curves.channelCurves[2]={{0,0},{.5,.6},{1,1}};
 const auto channelDoc=setRevisableAdjustments(legacyLoaded,layer.id,tiles,{curves}).finish(legacyLoaded->revision+1);expect(channelDoc->singleLayer().adjustments->policy==2,"Changed channel stack uses policy2");const auto channelPath=directory.filePath("channels-v5.cproj");saveProject(channelPath,channelDoc);const auto channelLoaded=loadProject(channelPath,tiles).document;expect(channelLoaded->singleLayer().adjustments->operations==std::vector<AdjustmentParameters>{curves},"Exact per-channel controls");expect(pack(channelLoaded->singleLayer().raster->pixel(0,0))==pack(channelDoc->singleLayer().raster->pixel(0,0)),"Per-channel effective bits");expect(channelLoaded->singleLayer().adjustments->source->id==layer.raster->id,"Per-channel retained source");
 const auto version5Path=directory.filePath("legacy-channels-v5.cproj");saveProject(version5Path,channelDoc);change(version5Path,"UPDATE project SET selection_json='{\"version\":1,\"shape\":\"rectangle\",\"bounds\":[0,0,2,1],\"inverted\":false}'; PRAGMA user_version=5");const auto version5=loadProject(version5Path,tiles).document;expect(version5->singleLayer().adjustments->operations==channelDoc->singleLayer().adjustments->operations,"Version5 unchanged channel parameters");expect(pack(version5->singleLayer().raster->pixel(0,0))==pack(channelDoc->singleLayer().raster->pixel(0,0))&&version5->singleLayer().raster->id==channelDoc->singleLayer().raster->id,"Version5 exact channel cache identity and bits");
 AdjustmentParameters maximal;maximal.kind=AdjustmentKind::Curves;maximal.curve.clear();for(auto& channel:maximal.channelCurves)channel.clear();
 for(int i=0;i<16;++i){const double input=double(i)/15;maximal.curve.push_back({input,.05+.9*input*input});for(int channel=0;channel<3;++channel)maximal.channelCurves[static_cast<std::size_t>(channel)].push_back({input,.01*(channel+1)+(.96-.01*channel)*input*input});}
 auto largeStack=std::make_shared<AdjustmentStack>();largeStack->source=layer.raster;largeStack->policy=2;largeStack->operations=std::vector<AdjustmentParameters>(16,maximal);auto largeCache=evaluateAdjustmentStack(*largeStack,tiles);const auto oneRecord=adjustmentParameters(*largeStack,*largeCache,Sampling::Bilinear);expect(oneRecord.size()*300>4*1024*1024,"Aggregate limit fixture is large enough");
 std::vector<LayerNode> excessiveNodes;for(int i=0;i<300;++i){auto node=layer;node.id=Id::generate();node.siblingOrder=i;node.raster=largeCache;node.adjustments=largeStack;excessiveNodes.push_back(std::move(node));}auto excessiveDoc=std::make_shared<const DocumentSnapshot>(original->id,4,2,150,std::move(excessiveNodes),2,original->selection);const auto priorChannelIdentity=fileIdentity(channelPath);SaveOptions refused;refused.expected=priorChannelIdentity;rejects([&]{saveProject(channelPath,excessiveDoc,refused);});expect(fileIdentity(channelPath)==priorChannelIdentity,"Aggregate metadata refusal preserves destination");expect(loadProject(channelPath,tiles).document->singleLayer().adjustments->operations==std::vector<AdjustmentParameters>{curves},"Previous channel project remains readable");
 std::cout<<"Revisable persistence tests passed\n";return 0;
 }catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
