#!/usr/bin/env python3
"""Regenerate/check the frozen FP32 Hard Mix classification thresholds."""
import argparse
import hashlib
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "core/hard_mix_thresholds.h"
SHADER = ROOT / "shaders/blend.comp"
KERNEL = ROOT / "vulkan/blend_kernel.cpp"


def decode(code):
    return code / 12.92 if code <= 0.04045 else ((code + 0.055) / 1.055) ** 2.4


def bits(value):
    return struct.unpack("<I", struct.pack("<f", value))[0]


def outputs():
    values = [bits(decode((q + 0.5) / 4096)) for q in range(4096)]
    digest = hashlib.sha256(b"".join(struct.pack("<I", value) for value in values)).hexdigest()
    header = ("#pragma once\n#include <array>\n#include <cstdint>\n\n"
              "namespace compositor::engine {\n"
              "// Generated by tools/generate_hard_mix_thresholds.py.\n"
              f"// Little-endian FP32 threshold SHA-256: {digest}\n"
              "inline constexpr std::array<std::uint32_t,4096> hardMixThresholdBits{\n")
    for offset in range(0, len(values), 8):
        header += "    " + ",".join(f"0x{value:08x}u" for value in values[offset:offset + 8]) + ",\n"
    header += "};\n}\n"
    return header, digest


def check_gpu_binding():
    shader = SHADER.read_text()
    kernel = KERNEL.read_text()
    if not re.search(r"layout\([^)]*binding\s*=\s*3[^)]*\)\s*readonly\s+buffer", shader):
        raise SystemExit("Hard Mix requires a shared readonly threshold SSBO at binding 3")
    if '#include "core/hard_mix_thresholds.h"' not in kernel:
        raise SystemExit("GPU threshold upload must include the frozen CPU threshold header")
    if not re.search(r"std::memcpy\(thresholds_\.mapped\(\),engine::hardMixThresholdBits\.data\(\),sizeof\(engine::hardMixThresholdBits\)\)", kernel):
        raise SystemExit("GPU threshold upload must use the entire frozen CPU threshold array")
    if "VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VulkanBuffer::Memory::Host,std::move(memory)" not in kernel:
        raise SystemExit("GPU threshold buffer must use the injected memory admission owner")
    if "buffers{source,backdrop,output,{thresholds_.handle(),thresholds_.bytes()}}" not in kernel:
        raise SystemExit("GPU threshold buffer must bind after source/backdrop/output at binding 3")
    if "uintBitsToFloat(" not in shader or "hardMixThresholdBits[" not in shader:
        raise SystemExit("GPU threshold fetch must reinterpret the shared frozen FP32 bits")
    if re.search(r"case\s+4095\s*:", shader):
        raise SystemExit("Hard Mix threshold switch must not be embedded in the shader")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="Regenerate the frozen CPU header used by the GPU upload")
    mode.add_argument("--write-header-only", action="store_true", help="Alias for --write")
    mode.add_argument("--check", action="store_true", help="Verify generated artifacts (default)")
    args = parser.parse_args()
    header, digest = outputs()
    if args.write or args.write_header_only:
        HEADER.write_text(header)
    elif HEADER.read_text() != header:
        raise SystemExit("Hard Mix generated header differs; regenerate with --write")
    check_gpu_binding()
    # These fixture pairs independently exercise each side of selected code
    # boundaries. Keep the GPU oracle's embedded reference bits synchronized.
    expected = []
    for q in (0, 1, 255, 511, 1023, 2047, 3071, 4094):
        expected.extend((bits(decode((q + 0.5) / 4096)), bits(decode((4095 - q) / 4096))))
    for name in ("blend_test.cpp", "gpu_blend_test.cpp"):
        fixture = (ROOT / "tests" / name).read_text()
        block = re.search(r"hardMixBoundaries\s*\{\{(.*?)\}\};", fixture, re.S)
        if not block:
            raise SystemExit(f"Missing Hard Mix analytical fixture in {name}")
        actual = [int(token, 16) for token in re.findall(r"0x([0-9a-fA-F]+)u", block.group(1))]
        if actual != expected:
            raise SystemExit(f"Hard Mix analytical fixture bits differ from frozen recipe in {name}")
    print(f"Hard Mix 4096 FP32 thresholds SHA-256 {digest}")


if __name__ == "__main__":
    main()
