# Build-generated, endian-independent uint32 words; no runtime shader paths.
file(READ "${INPUT}" words HEX)
string(LENGTH "${words}" length)
math(EXPR remainder "${length} % 8")
if(NOT remainder EQUAL 0 OR length LESS 40)
  message(FATAL_ERROR "Invalid SPIR-V word stream")
endif()
math(EXPR last "${length} - 8")
if(NOT DEFINED SYMBOL)
  set(SYMBOL compositorBlendSpv)
endif()
set(header "#pragma once\n#include <cstdint>\ninline constexpr std::uint32_t ${SYMBOL}[]={\n")
foreach(offset RANGE 0 ${last} 8)
  string(SUBSTRING "${words}" ${offset} 8 word)
  string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," word "${word}")
  string(APPEND header "${word}\n")
endforeach()
string(APPEND header "};\n")
file(WRITE "${OUTPUT}" "${header}")
